/*
	This script focuses on how to use the GROUP BY function effectively.
*/

--Finding total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS 'customer_count'
FROM gold.dim_customers
GROUP BY country
ORDER BY customer_count DESC

--Finding total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS 'customer_count'
FROM gold.dim_customers
GROUP BY gender
ORDER BY customer_count DESC

--Finding total products by category
SELECT
	category,
	COUNT(product_key) AS 'total_products'
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--Finding average cost of each category
SELECT
	category,
	AVG(product_cost) AS 'average_cost'
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

--Finding total revenue genrated for each category
SELECT
	p.category,
	SUM(s.price) AS 'revenue'
FROM gold.dim_products  AS p
LEFT JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY category
ORDER BY revenue DESC

--Finding revenue generated by each csustomer
SELECT
	s.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.price) AS 'customer_revenue'
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY s.customer_key,c.first_name,c.last_name
ORDER BY customer_revenue DESC

--Finding distribution of items sold across countries
SELECT
	c.country,
	SUM(s.quantity) AS 'customer_revenue'
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY customer_revenue DESC